spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: user
    password: password
    driver-class-name: org.postgresql.Driver
server:
  port: 8088
  address: 127.0.0.1

